# Generated by Buildr 1.4.0, change to your liking
# Version number for this release
VERSION_NUMBER = "0.0.1-SNAPSHOT"
# Group identifier for your projects
GROUP = "name.webdizz.liner"
COPYRIGHT = ""

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://localhost:8081/nexus/content/groups/public/"
Buildr.application.settings.build[:expire_time] = 0

GWT_GROUP = 'com.google.gwt'
GWT_VERSION = '2.0.4'
GWT = [
	"#{GWT_GROUP}:gwt-dev:jar:#{GWT_VERSION}",
	"#{GWT_GROUP}:gwt-servlet:jar:#{GWT_VERSION}",
	"#{GWT_GROUP}:gwt-user:jar:#{GWT_VERSION}",
        'com.googlecode.mvp4g:mvp4g:jar:1.1.0',
        'com.google.gwt.google-apis:gwt-language:jar:1.1.0',
        'com.googlecode.gwt-mobile-webkit:htnl5-database:jar:1.5.1'
]

TEST = [
	'org.mockito:mockito-all:jar:1.8.3',
	'junit:junit:jar:4.8.2'
]

desc "The Clt project"
define "liner" do

  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT

  define "clt-crx" do
	compile.with GWT, project('gwt-chrome-bridge')
    	test.with TEST
  end

  define "gwt-chrome-bridge" do
	compile.with GWT
	test.with TEST
	package :jar
  end

  define "gwt-chrome-bridge-test" do
  end

end
