package com.google.gwt.chrome.crx.client;

import com.google.gwt.core.client.EntryPoint;

/**
 * 
 * {@link GwtContentScriptEntryPoint} is a {@link ContentScript} the main
 * difference is it is generated by GWT compiler instead of simple JavaScript
 * file. Details at <a
 * href="http://code.google.com/chrome/extensions/content_scripts.html" >Content
 * Scripts</a>
 */
public abstract class GwtContentScriptEntryPoint implements EntryPoint {

	/**
	 * Should be implemented in you {@link GwtContentScriptEntryPoint}s.<br />
	 * This is a start point for {@link GwtContentScriptEntryPoint} code.
	 */
	abstract public void onScriptLoad();

	public void onModuleLoad() {
		onScriptLoad();
	}

	/**
	 * Attempts to connect to extension using specified connection name.
	 * 
	 * @param connectionName
	 *            the connection name
	 * @return {@link Port} through which messages can be sent and received with
	 *         the extension
	 */
	protected Port connect(final String connectionName) {
		return Chrome.getExtension().connect(connectionName);
	}
}
